# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-06 15:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('version', models.CharField(max_length=32)),
                ('beta', models.BooleanField(default=False)),
                ('release_notes', models.TextField()),
                ('url', models.URLField()),
                ('github_id', models.IntegerField()),
                ('time_created', models.DateTimeField()),
                ('time_push_sandbox', models.DateTimeField(blank=True, null=True)),
                ('time_push_prod', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['repo__product_name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('owner', models.CharField(max_length=255)),
                ('product_name', models.CharField(max_length=255)),
                ('github_id', models.IntegerField(blank=True, null=True)),
                ('url', models.URLField(max_length=255)),
            ],
            options={
                'ordering': ['name', 'owner'],
            },
        ),
        migrations.AddField(
            model_name='release',
            name='repo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='releases', to='repository.Repository'),
        ),
    ]
