# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-29 19:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0002_auto_20170711_2351'),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='tag',
            field=models.CharField(default='uat/Version 1', max_length=255),
            preserve_default=False,
        ),
    ]
