# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-06 19:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0002_auto_20170711_2351'),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='release_notes_html',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
