# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-06 23:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0004_delete_duplicate_releases'),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='is_removed',
            field=models.BooleanField(default=False),
        ),
    ]
