# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-12 22:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube_id', models.CharField(max_length=255)),
                ('json_str', models.TextField(blank=True, editable=False, null=True)),
                ('title', models.CharField(blank=True, editable=False, max_length=255, null=True)),
            ],
        ),
    ]
