# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-30 00:38
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('build_events', '0002_auto_20170829_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildresult',
            name='build_data',
            field=jsonfield.fields.JSONField(blank=True),
        ),
    ]
